### ISSUE TITLE
Error when loading player's head with '<head:%player_name%>'

### ISSUE THREAD

**Issue by SrBedrock** [Arasple/TrMenu#117]
## Menu:

```yml
Title: '&6» Sistema de Lojas!'

Shape:
  - BBBBBBBBB
  - B+B|AB=#B
  - BBBBBBBBB
  - BBBB-BBBB

Buttons:
  '#':
    display:
      material: <skull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDAxYWZlOTczYzU0ODJmZGM3MWU2YWExMDY5ODgzM2M3OWM0MzdmMjEzMDhlYTlhMWEwOTU3NDZlYzI3NGEwZiJ9fX0=>
      name: '&aSobre a Loja de Jogadores'
      lore:
      - ''
      - '&a• &fPara abrir/vender um item na loja'
      - '&f  coloque o item que deseja vender na mão'
      - '&f  e use &c/ploja sell &e[quantia] [preço]'
      - ''
      - '&a• &e[quantia] &a= Quantidade de item.'
      - '&a• &e[preço] &a= Valor de venda do item.'
      - ''
      - '&a• &fExemplo: &c/ploja sell &e64 100'
      - '&f  Você colocara 64 itens a venda por $100'
      - ''
      - '&aPara abrir a loja de player use &c/ploja'
    actions:
      all:
      - 'player: ploja'
      - 'refresh'
  '-':
    display:
      material: NETHER_STAR
      name: '&eMenu Principal'
      lore: []
    actions:
      all:
      - 'open: menu'
  +:
    display:
      material: '<head:%player_name%>'
      name: '&2• %vault_rank% %essentials_nickname%'
      lore:
      - '&e• &fSaldo: &2$ &a%vault_eco_balance_formatted%'
  '|':
    display:
      material: <skull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDNjYjI3OWZkMDYxZjQ2MjFlZTc1NGE0YWU3ZWEyZDllODFlOTVjYWU1Yzk1OWYzOWY0MmIzM2U5YWIzMTEifX19>
      name: '&e♕ &6Loja do Servidor &e♕'
      lore:
      - ''
      - '&a• Clique aqui para abrir a'
      - '&a  loja do server.'
      - ''
      - '&f  Acesse a loja direto com'
      - '&c  /sloja &fou &c/sshop'
    actions:
      all:
      - 'player: sloja'
      - 'refresh'
  =:
    display:
      material: <skull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzA5OGQ0ZWY0OGVlOWI5Y2NmMTM3MmEwYzVmYjlkYmU3MzUyZTFmYTJiNDg0OWJjM2RjNTQyMzdmNGU3YzU4OSJ9fX0=>
      name: '&e★ &6Loja de Jogadores &e★'
      lore:
      - ''
      - '&a• Clique aqui para abrir a'
      - '&a  loja de jogadores.'
      - ''
      - '&f  Acesse a loja direto com'
      - '&c  /ploja &fou &c/pshop'
    actions:
      all:
      - 'player: ploja'
      - 'refresh'
  A:
    display:
      material: <skull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDAxYWZlOTczYzU0ODJmZGM3MWU2YWExMDY5ODgzM2M3OWM0MzdmMjEzMDhlYTlhMWEwOTU3NDZlYzI3NGEwZiJ9fX0=>
      name: '&aSobre a Loja do Server &2'
      lore:
      - ''
      - '&a• &fPara vender para a loja do server'
      - ' &f  Use o comando &c/sell hand &e[quantia]'
      - ' &f  com o item na mão para vende-lô.'
      - ''
      - '&a• &fUse o comando &c/sell handall'
      - '&f  para vender todos os itens no'
      - '&f  inventário que são do mesmo'
      - '&f  tipo do item que está na mão.'
      - ''
      - '&a• &fUse o comando &c/sell all'
      - '&f  para vender todos os itens'
      - '&f  que estão no seu inventário.'
      - ''
      - '&aPara abrir a loja do server use &c/sloja'
    actions:
      all:
      - 'player: sloja'
      - 'refresh'
  B:
    display:
      material: GRAY_STAINED_GLASS_PANE
      name: '&f '
      lore: []
```

## settings.yml

```yml
#
# Configuration
#
Options:
  # Whether the debug mode should be enabled or not (more information will be sent to the console)
  Debug: false
  # Language of the plugin
  # Available： zh_CN, zh_TW, en_US, fr_FR
  Locale: en_US
  # Whether to hide the Logo of the plugin in the console on startup
  Hide-Logo: true
  # When enabled TrMenu will get the player heads datas from Mojang's API
  # [RECOMMENDED] If disabled, it will get them from https://api.minetools.eu/
  Skull-Mojang-API: false

#
# Get menus from a path leading to a folder or directly a menu
# Supports ItemRepo files to get pre-made items for your menus
#
Load-Menu-Files:
  - 'plugins/CustomMenusFolder'

#
# Actions Configuration
#
Actions:
  # Customize the words used to cancel an input catcher, supports regex
  Catcher-Cancel-Words:
    - '(?i)cancel|cancel!|quit|exit|end|stop|'

#
# Menu Items Configuration
#
Item:
  # Default color for items' names
  Default-Color-Name: '&7'
  # Default color for items' lores
  Default-Color-Lore: '&7'

#
# Actions Shortcuts Configuration
#
Shortcuts:
  Offhand: []
  Sneaking-Offhand: []
  Right-Click-Player: []
  Sneaking-Right-Click-Player: []
  PlayerInventory-Border-Right: []

#
# Register commands with actions and arguments
# Supports tab-completition !
# (WARNING: A server restart is required to add, change or remove commands)
#
RegisterCommands:
  # Command name
#  openMenus:
    # Command Aliases
#    aliases:
#      - teste
#      - teste2
    # Required permission
#    permission: null
    # Actions executed without any arguments
#    execute:
#      - 'tell: &7Argument `example` Required!'
    # Arguments with their actions
#    arguments:
#      example: 'open: example'
  menu:
    aliases: []
    permission: null
    execute:
      - 'open: menu'
    arguments: []
  ticket:
    aliases: []
    permission: null
    execute:
      - 'open: ticket'
    arguments: []
  kits:
    aliases: []
    permission: null
    execute:
      - 'open: kits'
    arguments: []
  stats:
    aliases: []
    permission: null
    execute:
      - 'open: stats'
    arguments: []
  prot:
    aliases:
      - plot
      - protecao
      - proteger
    permission: null
    execute:
      - 'open: protecao'
    arguments:
      criar: 'open: protecao-criar'
      config: 'open: protecao-loja'
      loja: 'open: protecao-loja'
      permissao: 'open: protecao-perm'
  baltop:
    aliases:
      - topsaldo
      - topmoney
      - baltop
      - balancetop
    permission: null
    execute:
      - 'open: baltop'
    arguments: []
  loja:
    aliases:
      - shop
    permission: null
    execute:
      - 'open: loja'
    arguments: []
  vipmenu:
    aliases:
      - viptime
      - vipstatus
    permission: 'armageddon.vip'
    execute:
      - 'open: vip-menu'
    arguments: []
#
# When enabled, TrMenu will ignore cancelled events monitored by some plugins
# If you encouter compatibilities issues, try to toggle the option.
#
Events-Ignore-Cancelled:
  PlayerCommandPreprocessEvent: true
  InventoryOpenEvent: true
  InventoryClickEvent: true

# --------------------------------------------- #
# HASH cdda5984fa5bcfa251d80a6084d69cac7fcd284d #
# --------------------------------------------- #
```

## Error on console:

```
[10:59:58 WARN]: [TrMenu] Plugin TrMenu v2.0 generated an exception while executing task 2574560
java.util.ConcurrentModificationException: null
at java.util.HashMap.computeIfAbsent(HashMap.java:1226) ~[?:?]
at me.arasple.mc.trmenu.utils.Skulls.getPlayerHead(Skulls.kt:37) ~[?:?]
at me.arasple.mc.trmenu.display.item.property.Mat.createItem(Mat.kt:40) ~[?:?]
at me.arasple.mc.trmenu.display.item.DynamicItem.releaseItem(DynamicItem.kt:34) ~[?:?]
at me.arasple.mc.trmenu.display.icon.IconDisplay.createDisplayItem(IconDisplay.kt:23) ~[?:?]
at me.arasple.mc.trmenu.display.Icon.setItemStack(Icon.kt:33) ~[?:?]
at me.arasple.mc.trmenu.display.Icon$displayItemStack$1.run(Icon.kt:42) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
```
