### ISSUE TITLE
V2菜单的Bindings.Commands中的命令覆盖问题

### ISSUE THREAD

**Issue by Score2** [Arasple/TrMenu#123]
在v1时，我在一个菜单使用Bindings.Commands来绑定命令来打开，以/help为例，我将一个菜单的打开命令设置为help，那么输入/help就打开了菜单，输入/help <args...> 以后该菜单不会打开。

但在v2，这恰恰相反，输入/help <args...>也仍然能打开被绑定命令的菜单。
希望能修复一下.

**Comment by Tanguygab** [comment]
```yml
Options:
  Arguments: true
Buttons:
...
```
