### ISSUE TITLE
Condition with placeholder superiorskyblock2

### ISSUE THREAD

**Issue by Galaxy-MAX** [Arasple/TrMenu#17]
i don't why but my condition not work when it's display when not display right just to do reopen menu
here is the code:

```YAML
  'A':
    condition: '"%superior_island_exits%" == "Yes"' #this is when player has island
    pri: 2
    display:
      mats: '<skull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTg4N2NjMzg4YzhkY2ZjZjFiYThhYTVjM2MxMDJkY2U5Y2Y3YjFiNjNlNzg2YjM0ZDRmMWMzNzk2ZDNlOWQ2MSJ9fX0===>'
      name: '&f&k||&r &c&lLÀM MỚI ĐẢO &f&k||&r'
      lore:
        - ''
        - '&fChỉ với một nhấn, bạn'
        - '&fcó thể bắt đầu lại từ'
        - '&ftừ đầu!!'
        - ''
        - '&e&l* &acʟιcκ тo ʙʀowsᴇ'
    slot:
      - 21
    actions:
      all: ['sound: BLOCK_NOTE_BLOCK_PLING-1-2']
      left:
        - 'Close'
        - 'COMMAND: superiorskyblock2:island admin disband'
      right:
        - 'Close'
        - 'COMMAND: superiorskyblock2:island admin disband'      
  'A-2':
    condition:  '"%superior_island_exits%" == "No"' #this is when player not has island
    pri: 3
    display:
      mats: '<skull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTg4N2NjMzg4YzhkY2ZjZjFiYThhYTVjM2MxMDJkY2U5Y2Y3YjFiNjNlNzg2YjM0ZDRmMWMzNzk2ZDNlOWQ2MSJ9fX0===>'
      name: '&f&k||&r &c&lLÀM MỚI ĐẢO &f&k||&r'
      lore:
        - ''
        - '&4KHÔNG ĐỦ ĐIỀU KIỆN'
        - ''
    slot:
      - 21
    actions:
      all: ['sound: BLOCK_NOTE_BLOCK_PLING-1-2']
```

**Comment by Galaxy-MAX** [comment]
this too :v
![image](https://user-images.githubusercontent.com/52485153/72680563-d6957280-3aed-11ea-9882-1c3a2b040339.png)

**Comment by Arasple** [comment]
Are you sure that %superior_island_exits% returns **yes** or **no** ?
Try to use /papi parse me %superior_island_exits%

**Comment by Galaxy-MAX** [comment]
sure i have try before i put it in

**Comment by Arasple** [comment]
Aha, I know, sorry, but this is not the way to write priority icons in TrMenu. Please try this

```YAML
  'A':
    condition:
    display:
      slot: [21]
      mats: '<skull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTg4N2NjMzg4YzhkY2ZjZjFiYThhYTVjM2MxMDJkY2U5Y2Y3YjFiNjNlNzg2YjM0ZDRmMWMzNzk2ZDNlOWQ2MSJ9fX0===>'
      name: '&f&k||&r &c&lLÀM MỚI ĐẢO &f&k||&r'
      lore:
        - ''
        - '&fChỉ với một nhấn, bạn'
        - '&fcó thể bắt đầu lại từ'
        - '&ftừ đầu!!'
        - ''
        - '&e&l* &acʟιcκ тo ʙʀowsᴇ'
    actions:
      all: ['sound: BLOCK_NOTE_BLOCK_PLING-1-2']
      left:
        - 'Close'
        - 'COMMAND: superiorskyblock2:island admin disband'
      right:
        - 'Close'
        - 'COMMAND: superiorskyblock2:island admin disband'
    icons:
      - condition:  '"%superior_island_exits%" == "No"' #this is when player not has island
        display:
          mats: '<skull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTg4N2NjMzg4YzhkY2ZjZjFiYThhYTVjM2MxMDJkY2U5Y2Y3YjFiNjNlNzg2YjM0ZDRmMWMzNzk2ZDNlOWQ2MSJ9fX0===>'
          name: '&f&k||&r &c&lLÀM MỚI ĐẢO &f&k||&r'
          lore:
          - ''
          - '&4KHÔNG ĐỦ ĐIỀU KIỆN'
          - ''
        actions:
          all: ['sound: BLOCK_NOTE_BLOCK_PLING-1-2']
```
