### ISSUE TITLE
Action OP not working

### ISSUE THREAD

**Issue by SrBedrock** [Arasple/TrMenu#28]
Hi Araple!
The OP action is not working.

```yml
  +:
    display:
      material: COMPASS
      name: '&a» Definir uma Warp!'
      lore:
      - ''
      - '&a• Clique aqui para definir'
      - '&a  uma warp com seu nome no'
      - '&a  local onde você está!'
      - ''
      - '&a• Para teleportar para a warp'
      - '&a  Use &c/warp &e%player_name%'
      - ''
      - '&c• Para alterar uma Warp já'
      - '&c  definida crie uma nova warp!'
      - ''
      - '&a• Crie uma warp direto com o'
      - '&a  comando: &c/setvipwarp'
    actions:
      all:
      - 'OP: setwarp %player_name%'
      - close
```

**Comment by Arasple** [comment]
Try to run command to test it
`/trmenu runAction <player> OP: setwarp %player_name%`

**Comment by SrBedrock** [comment]
Yep, same error, saying I don't have permission.

**Comment by Arasple** [comment]
Permission messages from Essentials, or other plugins? You could try to enable LuckPerms' verbose and see what permission it requires

**Comment by SrBedrock** [comment]
Permission messages from Essentials
Permission: `essentials.setwarp`

**Comment by Arasple** [comment]
That's weird. Do you disable the OP system in LuckPerms?

**Comment by SrBedrock** [comment]
Let me check.

**Comment by SrBedrock** [comment]
LuckPerms config
```yml
# +----------------------------------------------------------------------------------------------+ #
# | Server Operator (OP) settings                                                                | #
# +----------------------------------------------------------------------------------------------+ #

# Controls whether server operators should exist at all.
#
# - When set to 'false', all players will be de-opped, and the /op and /deop commands will be
#   disabled.
enable-ops: true

# Enables or disables a special permission based system in LuckPerms for controlling OP status.
#
# - If set to true, any user with the permission "luckperms.autoop" will automatically be granted
#   server operator status. This permission can be inherited, or set on specific servers/worlds,
#   temporarily, etc.
# - Additionally, setting this to true will force the "enable-ops" option above to false. All users
#   will be de-opped unless they have the permission node, and the op/deop commands will be
#   disabled.
# - It is recommended that you use this option instead of assigning a single '*' permission.
auto-op: false

# Defines if "opped" players should be able to use all LuckPerms commands by default.
#
# - Set to false to only allow users who have the permissions access to the commands
commands-allow-op: true
```

**Comment by SrBedrock** [comment]
Essentials plugin.yml
```yml
permissions:
  essentials.*:
    default: op
    description: Give players with op everything by default
    children:
      essentials.gamemode.*: true
  # These permissions can't be assigned from player-commands for compatibility reasons
  essentials.teleport.cooldown.bypass.tpa:
    default: true
    description: If the player does not have this permission, /tpa will have cooldown even with the parent bypass perm
  essentials.teleport.cooldown.bypass.back:
    default: true
    description: If the player does not have this permission, /back will have cooldown even with the parent bypass perm
  essentials.gamemode.*:
    default: op
    children:
      essentials.gamemode: true
      essentials.gamemode.others: true
      essentials.gamemode.all: true
  essentials.seen.extra:
    default: op
    children:
      essentials.seen.ip: true
      essentials.seen.location: true
  essentials.keepinv:
    default: false
    description: Controls whether players keep their inventory on death.
```
