### ISSUE TITLE
一个小小的建议

### ISSUE THREAD

**Issue by BeerMC** [Arasple/TrMenu#33]
**希望可以支持补全某些类型的指令的功能**
比如command: tpa @choose_online_player@
会向玩家弹出一个箱子界面，里面是在线玩家头像，点击其中一个，自动补全指令中的玩家名并执行。
这样的功能也可以拓展，比如
@choose_a_number_A_B@，选一个A至B范围的数字

**Comment by TSIXS** [comment]
关于这个话题，希望是这样进行支持：
- 能够自定义的玩家列表模板

下方是我想象中的节点：

```
Title: '自定义列表'
Shape:
- 'AAAAAAAAA'
- ''
- 'L       R'

Buttons:
  'A':
    # 列表形式展现Type类型物品, 每展现的物品的变量, 如果是OnlinePlayer, 在展示时显示使用被展列玩家的变量
    List:
      Type: OnlinePlayer
      display:
        # 展示目标玩家的头颅
        mats: '<head:%player_name%>'
        name: '传送到 %player_name%'
      actions:
        all:
        - 'command: tpa %player_name%'
  'L':
    display:
      mats: 1
      name: '上一页'
    actions:
      all:
      - '跳转A部分的上一页'
  'R':
    display:
      mats: 1
      name: '下一页'
    actions:
      all:
      - '跳转A部分的上一页'
```
