### ISSUE TITLE
提问 关于检测物品存在的表达式

### ISSUE THREAD

**Issue by yusisi08** [Arasple/TrMenu#5]
这个表达式我弄不太懂
      lore:
        - ''
        - ' &f&l收购钻石 *(9)'
        - ' &e预计获得金币 *(180)'
        - ''
        - '&a  >点击卖出<'
    actions:
      all: 'CONSOLE: clear %player_name% diamond 1<REQUIREMENT:%checkitem_mat:DIAMOND%>'
然鹅在试检测方法时却发现没有效果，就点击了并不会扣除钻石
我想写检测钻石>=9进行扣除并且给金钱

**Comment by Arasple** [comment]
%checkitem_mat:DIAMOND% 实际上是返回字符串 no 或 yes
`<REQUIREMENT:"%checkitem_mat:DIAMOND%" == "yes">`
平时你测试 PAPI 时可以通过命令来看看实际返回内容
`/papi parse <(playername)/me> <...args>`


但我将在 v1.07 更新中对这种情况做了主动兼容，新版中可以这样写
`<REQUIREMENT:%checkitem_mat:DIAMOND%>`

**Comment by Arasple** [comment]
对于你的需求可以这样写

```
    actions:
      all:
      - 'TITLE: <TITLE=&a&l出售成功><SUBTITLE=&e&l+ &6&l180 金币>'
      - 'CONSOLE: eco give %player_name% 180<REQUIREMENT:%checkitem_mat:DIAMOND,amt:9%>'
      - 'CONSOLE: clear %player_name% diamond 9<REQUIREMENT:%checkitem_mat:DIAMOND,amt:9%>'
```


稍完整点的优先级按钮可以这样写
```
    update: 20
    refresh-condition: 20
    display:
      mats: 'DIAMOND'
      name: '&bSell Diamond'
      lore:
      - ''
      - ' &f&l收购钻石 *(9)'
      - ' &e预计获得金币 *(180)'
      - ''
      - '&a >点击卖出<'
    icons:
      - condition: '%checkitem_mat:DIAMOND,amt:9%'
        actions:
          all:
          - 'TITLE: <TITLE=&a&l出售成功><SUBTITLE=&e&l+ &6&l180 金币>'
          - 'CONSOLE: eco give %player_name% 180'
          - 'CONSOLE: clear %player_name% diamond 9'
    actions:
      all:
      - 'tell: &c你没有足够的钻石'
```
