### ISSUE TITLE
关于Shape排版和GlobalButtions。

### ISSUE THREAD

**Issue by TSIXS** [Arasple/TrMenu#52]
#### 在原有的Shape的用法上来看，通常会出现“词穷”或者一些让强迫症不适
像原有的Shape会有一定的局限性，如下
```
Shape:
- '12345678'
- '90abcdef'
- 'ghijklmno'
- 'pqrstuvwx'
- 'yzABCDEFG'
```

#### 建议在原有Shape的基础上使其更加实用，如下：
```
Shape:
- ["Item1","Item2","Item3","Item4"]
- '  D A C  '
- ''

Buttons:
  'item1':
    display:
      mats: 1
  'item2':
    display:
      mats: 2
  'item3':
    display:
      mats: 3
  'item4':
    display:
      mats: 4
```
#### 上方Shape第一行也是List，可能影响到翻页，如下：
```
Shape:
- - ["Item1","Item2","Item3","Item4"]
  - '  D A C  '
  - ''
- - ["Item5","Item6","Item7","Item8"]
  - '  A B C  '
  - ''

Buttons:
  'item1':
    display:
      mats: 1
  'item2':
    display:
      mats: 2
  'item3':
    display:
      mats: 3
  'item4':
    display:
      mats: 4
  'item5':
    display:
      mats: 5
  'item6':
    display:
      mats: 6
  'item7':
    display:
      mats: 7
  'item8':
    display:
      mats: 8
```

但按常理来看，似乎无法读取，因为List<List<这里不可能有两种元素>>
那么应该先使用Object来判断，如下：
```
for (Object i : config.getList("list")) {
    if (i instanceof List) {
        for (Object ii : (List) i) {
            //检测到是List
        }
    } else {
        //非List
    }
}
```
以上代码仅供参考。

## 关于GlobalButtions（全局按钮）
关于这个建议，又让我想起了 #18 。
从另一个菜单配置文件调用按钮，甚至配置文件也可以随意，只要其中包含Buttons。
以下是我想象中的格式：（Shape基于上面的报告）
```
Title: 'GlobalButtions Test'

# 调用的按钮，“文件名_”作为开头，后调用。
Shape:
- ["test_A","menu_1"]
- '2'

# 调用其它配置文件的按钮
Extends-Buttons:
- 'C:\test.yml'
- 'C:\menu.yml'

Buttions:
  'a':
    display:
      mats: 2
```
