### ISSUE TITLE
建议在 display中的name和lore节点也进行支持request

### ISSUE THREAD

**Issue by TSIXS** [Arasple/TrMenu#54]
建议在 display中的name和lore节点也进行支持request，方便在一些商店进行显示“金币不足”，“可以购买”等，虽然可以通过icons优先级实现，但是写起来麻烦，有时候节点多起来，难以管理。
配置文件例子：
```
Buttons:
  '1':
    display:
      name: 
      - '&6商店<Require:player.hasPermission("trmenu.test")>'
      - '&c商店<Require:!player.hasPermission("trmenu.test")>'
      lore:
      - ''
      - ''
      - '&a&l可购买<Require:player.hasPermission("trmenu.test")>'
      - '&c&l无法购买<Require:!player.hasPermission("trmenu.test")>'
```
