### ISSUE TITLE
Set-shape in Open-Actions and InputCatcher

### ISSUE THREAD

**Issue by Tanguygab** [Arasple/TrMenu#63]
Hey, I have some problems with the `set-shape` action, it doesn't seem to work neither when I put it in `Open-Actions` nor the Input Catcher actions.
I even tried to add <wait:10> to the action but thrown an error https://hastebin.com/feluvewocu.bash
Also, in the Input Catcher I tried to reopen the menu with the command (from here it works) but the set-shape action doesn't work and I can't add <wait:10> because of the <> and it throws another error. I would suggest to have another format for the Input Catcher that would accepts Requirements for some commands and not all and others actions options like Wait:
(idk if it can work with this syntax but it's just a suggestion)
```
actions:
  all:
    - Catcher:
       type: SIGN/CHAT/ANVIL #I know you added anvil to the pro version, but it would still be cool for the normal one =)
       keep-open: true/false
       before-actions:
         - "tell:&3&lPlease type a &fvalue"
         - "tell:&3&lType &fcancel &3&l to cancel"
       cancel-actions:
         - "&7Canceled..."
         - "close"
       actions:
         - "set-shape: $input<TrUtils.isNumber($input)>"
         - "break<Trutils.isNumber($input)>"
         - "tell:&cYou didn't type a value"
         - "close"
```
