### ISSUE TITLE
REQUIREMENT条件问题

### ISSUE THREAD

**Issue by RusBrook** [Arasple/TrMenu#7]
服务端核心: spigot-1.12.2
插件列表:
PlaceholderAPI
Taboolib
Trmenu
Vault
问题:
REQUIREMENT条件无法正常使用
<REQUIREMENT:%vault_eco_balance% >= 500>无法使用
<REQUIREMENT:%vault_eco_balance% <= 500>无法使用
出错配置:
        actions:
          all:
            - 'close'
            - 'tell: &c余额不足 500 金币.<requirement:%vault_eco_balance% >= 500>'
            - 'break<requirement:%vault_eco_balance% >= 500>'
            - 'console: give %player_name% diamond 1'
            - 'console: eco take %player_name% 500'
            - 'tell: &a你支付了 &e500 &a金币 购买了一颗钻石!'
![image](https://user-images.githubusercontent.com/44542189/69008181-99dcbc00-0982-11ea-9ac4-918296f988f8.png)
货币不足但是仍会执行操作,貌似无报错

**Comment by Arasple** [comment]
may fixed in 1.1

```YAML
  'A':
    update: 20
    display:
      mats: 'apple'
      lore:
        - - ''
          - '&f· &7售价: &e100$'
          - '&f· &7收购: &220$'
          - ''
          - '&3左键点击购买 &8| &6右键点击出售'
          - ''
    actions:
      all: ['sound: BLOCK_NOTE_BLOCK_PLING-1-2']
      left:
        - 'Close'
        - 'Tell: &c你没有足够的余额_||_Break:<Requirement: %vault_eco_balance% < 100>'
        - 'Console: eco take %player_name% 100'
        - 'Console: give %player_name% apple 1'
        - 'Title: <title=&3&l操作成功><subtitle=&a&l苹果 &cx1 &7已发放至你背包...>'
      right:
        - 'Close'
        - 'Tell: &c你没有苹果_||_Break:<Requirement: "%checkitem_mat:APPLE,amt:1%" == "no">'
        - 'Console: eco give %player_name% 20'
        - 'Console: clear %player_name% apple 1'
```
