### ISSUE TITLE
Input Catcher Suggestions

### ISSUE THREAD

**Issue by Tanguygab** [Arasple/TrMenu#93]
Yup, I was right, Input Catcher's the next :D

So, here we go ! :
- - [x] Update for the Input Catcher's look as asked [here](https://github.com/Arasple/TrMenu/issues/63) that would fix [this](https://github.com/Arasple/TrMenu/issues/63#issuecomment-597655666) and [this](https://github.com/Arasple/TrMenu/issues/72) problems:
```yml
actions:
  all:
    - Catcher:
       type: SIGN/CHAT/ANVIL #I know you added anvil to the pro version, but it would still be cool for the normal one =)
       keep-open: true/false
       before-actions:
         - "tell:&3&lPlease type a &fvalue"
         - "tell:&3&lType &fcancel &3&l to cancel"
       cancel-actions:
         - "&7Canceled..."
         - "close"
       actions:
         - "set-shape: $input_||_Break<TrUtils.isNumber($input)>"
         - "tell:&cYou didn't type a value"
         - "AskAgain"
```
 - - [x] With that new look, if `keep-open` is enabled, all [Menu Actions](https://trmenu.trixey.cn/actions/menu-actions) should work (because it isn't currently the case =/ or at least for the two most important actions : set-shape and set-args)
 - - [x] New `AskAgain` action that will ask the same input catcher again,
 - - [x] Actions placed after the input catcher are executed after it is ended (they won't be executed after the first time if the `AskAgain` action is executed, they will have to wait until it isn't executed anymore)
 - - [x] Possibility to have multiples input catchers as asked [here](https://github.com/Arasple/TrMenu/issues/69), their output could be used in other actions with $input or $input0 for the first catcher, then $input1, $input2, $input3 etc....

I think I'm done here :D
